---
language: python
python: 3.8

cache:
  pip: true

branches:
  only:
    - master
    - /^travis.*/
    - /^v.*/

stages:
  - name: test
  - name: deploy
    if: branch =~ ^v.*$

jobs:
  include:
    - stage: test
      install: pip install tox tox-travis coverage
      script: tox
      after_success: bash <(curl -s https://codecov.io/bash)

    - stage: deploy
      install: skip
      script: skip
      deploy:
        - provider: pypi
          user: "__token__"
          password: $PYPI_TOKEN
          distributions: "sdist bdist_wheel"
          skip_existing: true
          on:
            all_branches: true
