name: publish-release

on:
  release:
    types: [ created ]


jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.x"

      - name: Install pypa/build
        run: python3 -m pip install build --user

      - name: Build a binary wheel and a source tarball
        run: python3 -m build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4.3.3
        with:
          name: client-python-distributions
          path: dist/

  publish-test:
    runs-on: ubuntu-latest
    needs: package
    environment:
      name: testpypi
      url: https://test.pypi.org/p/animatedledstrip-client
    permissions:
      id-token: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: client-python-distributions
          path: dist/

      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

#  publish:
#    runs-on: ubuntu-latest
#    needs: package
#    environment:
#      name: pypi
#      url: https://pypi.org/p/animatedledstrip-client
#    permissions:
#      id-token: write
#    steps:
#      - name: Download artifact
#        uses: actions/download-artifact@v4.1.7
#        with:
#          name: client-python-distributions
#          path: dist/
#
#      - name: Publish to PyPi
#        uses: pypa/gh-action-pypi-publish@release/v1